// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "engine": string;
      "pdftranslate.service": string;
      "ollama.url": string;
      "ollama.model": string;
      "requestGapMs": number;
      "maxConcurrent": number;
      "maxCharsPerRequest": number;
      "maxBatchParagraphs": number;
      "maxConsecutiveErrors": number;
      "requestTimeoutMs": number;
      "skipLastPages": number;
    };
  }
}
